name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  video_player: ^2.10.0
  file_picker: ^10.1.9
  movie_creator:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/data/
    - assets/font/
    - assets/imgs/
    - assets/imgs/album/
    - assets/imgs/bg/
    - assets/imgs/cover/
    - assets/imgs/frames/
    - assets/imgs/gif/
    - assets/imgs/logo/
    - assets/imgs/trans/
    - assets/lottie/
    - assets/video/
