name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file_picker: ^6.2.0
  file_saver: ^0.2.12
  permission_handler: ^11.3.0
  open_file: ^3.3.2
  flutter:
    sdk: flutter

  movie_creator:
    path: ../
  path: ^1.9.0
  flutter_hooks: ^0.20.5
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/big_buck_bunny_0_30.webm
    - assets/Baloo2-Medium.ttf
    - assets/audio/
    - assets/data/
    - assets/font/
    - assets/imgs/
    - assets/imgs/logo/
    - assets/imgs/album/
    - assets/imgs/bg/
    - assets/imgs/gif/
    - assets/lottie/
    - assets/video/
