name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file_picker: ^6.2.0
  file_saver: ^0.2.12
  permission_handler: ^11.3.0
  open_file: ^3.3.2
  flutter:
    sdk: flutter

  movie_creator:
    path: ../
  path: ^1.9.0
  flutter_hooks: ^0.20.5
  go_router: ^13.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  custom_lint: ^0.5.11
  flutter_lints: ^3.0.1

  go_router_builder: ^2.4.1
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/big_buck_bunny_0_30.webm
    - assets/Baloo2-Medium.ttf
    - assets/audio/
    - assets/data/
    - assets/font/
    - assets/imgs/
    - assets/imgs/logo/
    - assets/imgs/album/
    - assets/imgs/bg/
    - assets/imgs/gif/
    - assets/lottie/
    - assets/video/
