name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  movie_creator:
    path: ../
  file_picker: ^8.1.2
  permission_handler: ^11.3.1
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.7.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/data/
    - assets/font/
    - assets/imgs/
    - assets/imgs/album/
    - assets/imgs/bg/
    - assets/imgs/cover/
    - assets/imgs/frames/
    - assets/imgs/gif/
    - assets/imgs/logo/
    - assets/imgs/trans/
    - assets/lottie/
    - assets/video/
