include: package:very_good_analysis/analysis_options.9.0.0.yaml

analyzer:
  errors:
    one_member_abstracts: ignore

linter:
  rules:
    sort_pub_dependencies: false
    public_member_api_docs: false
    require_trailing_commas: false
    no_adjacent_strings_in_list: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
