name: movie_creator
description: movie_creator is a flutter package for short video editing with just use scenes and layers like other video editing softwares.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0

  ffmpeg_kit_flutter_full: 6.0.3-LTS
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.2
  logger: ^2.0.2+1

dev_dependencies:
  very_good_analysis: ^5.1.0
