name: movie_creator
description: movie_creator is a flutter package for short video editing with just use scenes and layers like other video editing softwares.
version: 0.0.1
repository: https://github.com/thitlwincoder/movie_creator
issue_tracker: https://github.com/thitlwincoder/movie_creator/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

funding:
  - https://paypal.me/thitlwinsoe260
  - https://ko-fi.com/thitlwincoder

topics:
  - movie
  - creator
  - ffmpeg

dependencies:
  async: ^2.11.0

  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4
  logger: ^2.4.0
  ffmpeg_kit_flutter_minimal: ^6.0.4

dev_dependencies:
  very_good_analysis: ^9.0.0
