name: movie_flutter
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  async: ^2.11.0

  ffmpeg_kit_flutter_full: 6.0.3-LTS
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.2
  logger: ^2.0.2+1

dev_dependencies:
  very_good_analysis: ^5.1.0
